version: '2'
services:
    pharmasoftapp-app:
        image: pharmasoftapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pharmasoftapp-postgresql:5432/pharmasoftApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pharmasoftapp-postgresql:
        extends:
            file: postgresql.yml
            service: pharmasoftapp-postgresql
