version: '2'
services:
    pharmasoftapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/pharmasoftApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pharmasoftApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
